dist: xenial
language: python
python: Python 3.9-dev

install:
  - pip install -r requirements.txt


script:
  - pylint hospital_app
  - coverage run -m unittest discover hospital/tests
  - coverage report

after_success:
  - coveralls
