language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=/home/travis/build/XValentavr/EpamFinalFlaskProject/hospital_app/

script:
  - pylint department_app
  - coverage run -m unittest discover hospital_app/tests
  - coverage report

after_success:
  - coveralls