dist: xenial
language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

  — pytest --cov=home/travis/build/XValentavr/EPAMFlaskFinalProject/hospital_app/tests
after_success:
  — coveralls