language: python
python:
  - "3.9"
services:
  - mysql
install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
  - pylint hospital_app
  - coverage report

after_success:
  - coveralls