language: python
python:
  - "3.9"
services:
  - mysql
install:
  - pip install -r requirements.txt

before_script:
  - mysql -c 'create database travis_ci_test;' -U mysql
  - mysql -c "CREATE USER foo WITH PASSWORD 'root';" -U mysql

script:
  - pylint hospital_app
  - coverage run -m unittest discover hospital_app/tests
  - coverage report

after_success:
  - coveralls