dist: xenial
language: python
python:
  - "3.9.7"

install:
  - pip install -r requirements.txt


script:
  - pylint hospital_app
  - coverage run -m unittest discover hospital/tests
  - coverage report

after_success:
  - coveralls
