"""empty message

Revision ID: d284b0652701
Revises: fb6419f5f212
Create Date: 2021-12-07 16:46:21.553317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd284b0652701'
down_revision = 'fb6419f5f212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('avatar', sa.BLOB(), nullable=True))
    op.add_column('admin', sa.Column('full_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'full_name')
    op.drop_column('admin', 'avatar')
    # ### end Alembic commands ###
